### ISSUE TITLE
Autocompletion does not work and no suggestions pop up

### ISSUE THREAD

**Issue by vincentwen1995** [wenmin-wu/jupyter-tabnine#15]
**OS**: Windows 10 X64 Enterprise
**Python interpreter**: Python 3.7.5 (Anaconda)
**Jupyter version**: 
```
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : 4.6.0
ipython          : 7.10.2
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
```
**Description**:
After following the instructions to install and enable the extension, in the notebook the extension simply does not work (no suggestion list). 
I used the debug mode to check the error message, and this is what I have after opening a notebook and typing a letter to trigger the autocompletion:
```
[E 12:33:11.390 NotebookApp] Uncaught exception GET /tabnine?data=%7B%22version%22%3A%221.0.7%22%2C%22request%22%3A%7B%22Autocomplete%22%3A%7B%22...
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/tabnine?data=%7B%22version%22%3A%221.0.7%22%2C%22request%22%3A%7B%22Autocomplete%22%3A%7B%22...', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "path-to-anaconda3\envs\general\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "path-to-anaconda3\envs\general\lib\site-packages\jupyter_tabnine-1.0.2-py3.7.egg\jupyter_tabnine\handler.py", line 13, in get
        response = self.tabnine.request(request_data)
      File "path-to-anaconda3\envs\general\lib\site-packages\jupyter_tabnine-1.0.2-py3.7.egg\jupyter_tabnine\tabnine.py", line 76, in request
        proc = self._get_running_tabnine()
      File "path-to-anaconda3\envs\general\lib\site-packages\jupyter_tabnine-1.0.2-py3.7.egg\jupyter_tabnine\tabnine.py", line 115, in _get_running_tabnine
        self._restart()
      File "path-to-anaconda3\envs\general\lib\site-packages\jupyter_tabnine-1.0.2-py3.7.egg\jupyter_tabnine\tabnine.py", line 110, in _restart
        stderr=subprocess.DEVNULL,
      File "path-to-anaconda3\envs\general\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "path-to-anaconda3\envs\general\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    OSError: [WinError 193] %1 is not a valid Win32 application
[D 12:33:11.393 NotebookApp] Using contents: services/contents
[D 12:33:11.395 NotebookApp] Using contents: services/contents
[E 12:33:11.400 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept": "*/*",
      "X-Requested-With": "XMLHttpRequest",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8888/notebooks/notebooks/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|68c99bb7|08b968eee94d37a6553c5c0309a7f367|1577123162; username-localhost-8888=\"2|1:0|10:1579519975|23:username-localhost-8888|44:NjM5Njc4NTcxNjA2NDEzMzhmMWE1NjMxOTdiMWQ2ODU=|67ed429e0eba414629080875a41de944d2561cf2da4333ad5a5e214b7e43b304\""
    }
```
As stated in the error `OSError: [WinError 193] %1 is not a valid Win32 application`, I checked the binaries of TabNine and found that TabNine.exe indeed could not be run directly, but I am not sure whether this is the problem.
To add to the problem, I am using a company laptop with non-admin user access, but I installed with the `--user` flag which shall be fine.

**Comment by vincentwen1995** [comment]
OK, pretty easy solution... I noticed that when booting Jupyter Notebook, a binary file check is done by the **TabNineDownloader**. Therefore, I manually deleted the binary file TabNine.exe and let the downloader update it, which solved the problem.
