### ISSUE TITLE
ModuleNotFoundError: No module named 'jupyter_tabnine'

### ISSUE THREAD

**Issue by Rouizi** [wenmin-wu/jupyter-tabnine#21]
I tried to install jupyter tabnine extension like this:

    pip3 install jupyter-tabnine
    jupyter nbextension install

with the second command I have this error:

    Installing /home/rouizi/.local/lib/python3.6/site-packages/jupyter_tabnine/static -> jupyter_tabnine
    Traceback (most recent call last):
      File "/home/rouizi/.local/bin/jupyter-nbextension", line 11, in <module>
        sys.exit(main())
      File "/home/rouizi/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 268, in 
    launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/home/rouizi/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in 
    launch_instance
        app.start()
      File "/home/rouizi/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 983, in start
        super(NBExtensionApp, self).start()
      File "/home/rouizi/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 257, in start
        self.subapp.start()
      File "/home/rouizi/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 711, in start
        self.install_extensions()
      File "/home/rouizi/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 690, in 
    install_extensions
        **kwargs
      File "/home/rouizi/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 220, in 
    install_nbextension_python
        destination=dest, logger=logger
      File "/home/rouizi/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 121, in 
    install_nbextension
        ensure_dir_exists(nbext)
      File "/home/rouizi/.local/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in 
    ensure_dir_exists
        os.makedirs(path, mode=mode)
      File "/usr/lib/python3.6/os.py", line 210, in makedirs
        makedirs(head, mode, exist_ok)
      File "/usr/lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

So I tried with `sudo`:

    sudo jupyter nbextension install --py jupyter_tabnine

    Traceback (most recent call last):
      File "/snap/jupyter/6/bin/jupyter-nbextension", line 11, in <module>
        sys.exit(main())
      File "/snap/jupyter/6/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in 
    launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/snap/jupyter/6/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in 
    launch_instance
        app.start()
      File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/nbextensions.py", line 988, in start
        super(NBExtensionApp, self).start()
      File "/snap/jupyter/6/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
        self.subapp.start()
      File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/nbextensions.py", line 716, in start
        self.install_extensions()
      File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/nbextensions.py", line 695, in 
    install_extensions
        **kwargs
      File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in 
    install_nbextension_python
        m, nbexts = _get_nbextension_metadata(module)
      File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in 
    _get_nbextension_metadata
        m = import_item(module)
      File "/snap/jupyter/6/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in 
    import_item
        return __import__(parts[0])
    ModuleNotFoundError: No module named 'jupyter_tabnine'

How can I fix this ?

**Comment by Starboomz** [comment]
I am having the same issues too!

**Comment by qingfeng1996** [comment]
same, the instruction must be more clear, much trouble caused by it

**Comment by wenmin-wu** [comment]
Please try these commands, which will install jupyter-tabine under user dir.
```
pip3 install jupyter-tabnine --user
jupyter nbextension install --py jupyter_tabnine --user
jupyter nbextension enable --py jupyter_tabnine --user
jupyter serverextension enable --py jupyter_tabnine --user
```

**Comment by wenmin-wu** [comment]
> same, the instruction must be more clear, much trouble caused by it

Thanks for your comment, I updated the `README.md`, the detail installation instruction may be misleading to some users.

**Comment by briancullinan** [comment]
I am still getting this error even with --user option.

**Comment by Betristor** [comment]
Yeah, I have encountered the same issue now.
