### ISSUE TITLE
Follow the install command but failed to work

### ISSUE THREAD

**Issue by qingfeng1996** [wenmin-wu/jupyter-tabnine#34]
the error message when running jupyter notebook

> 404 GET /nbextensions/jupyter-tabnine.js?v=20200415150256 (::1) 44.17ms referer=http://localhost:8888/notebooks/%E6%9C%AA%E5%91%BD%E5%90%8D.ipynb?kernel_name=python3
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 579, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 354, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 379, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/IPython/core/completer.py", line 1815, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/IPython/core/completer.py", line 1859, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/IPython/core/completer.py", line 1983, in _complete
    text = self.splitter.split_line(line_buffer, cursor_pos)
  File "/Users/wuyoudong/opt/anaconda3/lib/python3.7/site-packages/IPython/core/completer.py", line 562, in split_line
    l = line if cursor_pos is None else line[:cursor_pos]
TypeError: 'NoneType' object is not subscriptable

also if I enter
`jupyter nbextension list`

it shows

> jupyter-tabnine  enabled 
>  - Validating: problems found:
       - require?  X jupyter-tabnine

pls help, thanks.

**Comment by wenmin-wu** [comment]
seems you didn't install the package correctly, please follow these commands:
```
pip install jupyter-tabnine --user
jupyter nbextension install --py jupyter_tabnine --user
jupyter nbextension enable --py jupyter_tabnine --user
jupyter serverextension enable --py jupyter_tabnine --user
```

**Comment by wenmin-wu** [comment]
Close due to no update for 5 days.
