### ISSUE TITLE
ModuleNotFoundError: No module named 'jupyter_tabnine'

### ISSUE THREAD

**Issue by leeyunhome** [wenmin-wu/jupyter-tabnine#62]
Hello,
Thank you for your effort.

`(py37) E:\coding2>pip3 install jupyter-tabnine --user
Requirement already satisfied: jupyter-tabnine in c:\users\neuez\appdata\roaming\python\python37\site-packages (1.1.0)
Requirement already satisfied: notebook>=4.2 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from jupyter-tabnine) (6.2.0)
Requirement already satisfied: ipython in c:\coding\anaconda3\envs\py37\lib\site-packages (from jupyter-tabnine) (7.19.0)
Requirement already satisfied: jupyter-core in c:\coding\anaconda3\envs\py37\lib\site-packages (from jupyter-tabnine) (4.7.0)
Requirement already satisfied: nbconvert in c:\users\neuez\appdata\roaming\python\python37\site-packages (from jupyter-tabnine) (6.0.7)
Requirement already satisfied: traitlets>=4.2.1 in c:\coding\anaconda3\envs\py37\lib\site-packages (from notebook>=4.2->jupyter-tabnine) (5.0.5)
Requirement already satisfied: ipykernel in c:\coding\anaconda3\envs\py37\lib\site-packages (from notebook>=4.2->jupyter-tabnine) (5.4.3)
Requirement already satisfied: argon2-cffi in c:\users\neuez\appdata\roaming\python\python37\site-packages (from notebook>=4.2->jupyter-tabnine) (20.1.0)
Requirement already satisfied: nbformat in c:\users\neuez\appdata\roaming\python\python37\site-packages (from notebook>=4.2->jupyter-tabnine) (5.1.2)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\coding\anaconda3\envs\py37\lib\site-packages (from notebook>=4.2->jupyter-tabnine) (6.1.11)
Requirement already satisfied: prometheus-client in c:\users\neuez\appdata\roaming\python\python37\site-packages (from notebook>=4.2->jupyter-tabnine) (0.9.0)
Requirement already satisfied: jinja2 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from notebook>=4.2->jupyter-tabnine) (2.11.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from notebook>=4.2->jupyter-tabnine) (0.9.2)
Requirement already satisfied: pyzmq>=17 in c:\coding\anaconda3\envs\py37\lib\site-packages (from notebook>=4.2->jupyter-tabnine) (22.0.2)
Requirement already satisfied: tornado>=6.1 in c:\coding\anaconda3\envs\py37\lib\site-packages (from notebook>=4.2->jupyter-tabnine) (6.1)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from notebook>=4.2->jupyter-tabnine) (1.5.0)
Requirement already satisfied: ipython-genutils in c:\coding\anaconda3\envs\py37\lib\site-packages (from notebook>=4.2->jupyter-tabnine) (0.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\coding\anaconda3\envs\py37\lib\site-packages (from jupyter-client>=5.3.4->notebook>=4.2->jupyter-tabnine) (2.8.1)
Requirement already satisfied: pywin32>=1.0 in c:\coding\anaconda3\envs\py37\lib\site-packages (from jupyter-core->jupyter-tabnine) (300)
Requirement already satisfied: six>=1.5 in c:\coding\anaconda3\envs\py37\lib\site-packages (from python-dateutil>=2.1->jupyter-client>=5.3.4->notebook>=4.2->jupyter-tabnine) (1.15.0)
Requirement already satisfied: pywinpty>=0.5 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from terminado>=0.8.3->notebook>=4.2->jupyter-tabnine) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from argon2-cffi->notebook>=4.2->jupyter-tabnine) (1.14.4)
Requirement already satisfied: pycparser in c:\users\neuez\appdata\roaming\python\python37\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.2->jupyter-tabnine) (2.20)
Requirement already satisfied: decorator in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (4.4.2)
Requirement already satisfied: pygments in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (2.7.4)
Requirement already satisfied: colorama in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (0.4.4)
Requirement already satisfied: setuptools>=18.5 in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (52.0.0.post20210125)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (3.0.14)
Requirement already satisfied: jedi>=0.10 in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (0.18.0)
Requirement already satisfied: backcall in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (0.2.0)
Requirement already satisfied: pickleshare in c:\coding\anaconda3\envs\py37\lib\site-packages (from ipython->jupyter-tabnine) (0.7.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\coding\anaconda3\envs\py37\lib\site-packages (from jedi>=0.10->ipython->jupyter-tabnine) (0.8.1)
Requirement already satisfied: wcwidth in c:\coding\anaconda3\envs\py37\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyter-tabnine) (0.2.5)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from jinja2->notebook>=4.2->jupyter-tabnine) (1.1.1)
Requirement already satisfied: bleach in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (3.2.3)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (0.3)
Requirement already satisfied: defusedxml in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (0.6.0)
Requirement already satisfied: testpath in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (0.4.4)
Requirement already satisfied: jupyterlab-pygments in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (0.1.2)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (0.5.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbconvert->jupyter-tabnine) (1.4.3)
Requirement already satisfied: async-generator in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-tabnine) (1.10)
Requirement already satisfied: nest-asyncio in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-tabnine) (1.5.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from nbformat->notebook>=4.2->jupyter-tabnine) (3.2.0)
Requirement already satisfied: importlib-metadata in c:\coding\anaconda3\envs\py37\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.2->jupyter-tabnine) (3.4.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.2->jupyter-tabnine) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.2->jupyter-tabnine) (20.3.0)
Requirement already satisfied: packaging in c:\users\neuez\appdata\roaming\python\python37\site-packages (from bleach->nbconvert->jupyter-tabnine) (20.9)
Requirement already satisfied: webencodings in c:\users\neuez\appdata\roaming\python\python37\site-packages (from bleach->nbconvert->jupyter-tabnine) (0.5.1)
Requirement already satisfied: zipp>=0.5 in c:\coding\anaconda3\envs\py37\lib\site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.2->jupyter-tabnine) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\coding\anaconda3\envs\py37\lib\site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.2->jupyter-tabnine) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\neuez\appdata\roaming\python\python37\site-packages (from packaging->bleach->nbconvert->jupyter-tabnine) (2.4.7)
-------------------------------------------------------------------------------------------------------------
(py37) E:\coding2>jupyter nbextension install --py jupyter_tabnine --user
Traceback (most recent call last):
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\neuez\AppData\Local\Programs\Python\Python39\Scripts\jupyter-nbextension.EXE\__main__.py", line 7, in <module>
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 980, in start
    super().start()
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\jupyter_core\application.py", line 243, in start
    self.subapp.start()
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 708, in start
    self.install_extensions()
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 679, in install_extensions
    full_dests = install(self.extra_args[0],
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "c:\users\neuez\appdata\local\programs\python\python39\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'jupyter_tabnine'

(py37) E:\coding2>`

Can you tell me how to resolve this issue?

Thank you.

**Comment by briancullinan** [comment]
Duplicate of https://github.com/codota/jupyter-tabnine/issues/21

**Comment by gsangeryee** [comment]
If you use a virtual python env like conda, you should activate your python env that you often used first.
