### ISSUE TITLE
How do I install this with Anaconda?

### ISSUE THREAD

**Issue by Clorky** [wenmin-wu/jupyter-tabnine#9]
Hello, I'm using Anaconda. Can't seem to install it with: `pip3 install jupyter-tabnine [--user][--upgrade]` 

**Throws out this error:**

> ERROR: Exception:
> Traceback (most recent call last):
>   File "e:\anaconda\lib\site-packages\pip\_vendor\packaging\requirements.py", line 93, in __init__
>     req = REQUIREMENT.parseString(requirement_string)
>   File "e:\anaconda\lib\site-packages\pip\_vendor\pyparsing.py", line 1939, in parseString
>     raise exc
>   File "e:\anaconda\lib\site-packages\pip\_vendor\pyparsing.py", line 1929, in parseString
>     loc, tokens = self._parse(instring, 0)
>   File "e:\anaconda\lib\site-packages\pip\_vendor\pyparsing.py", line 1669, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "e:\anaconda\lib\site-packages\pip\_vendor\pyparsing.py", line 4037, in parseImpl
>     loc, exprtokens = e._parse(instring, loc, doActions)
>   File "e:\anaconda\lib\site-packages\pip\_vendor\pyparsing.py", line 1673, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "e:\anaconda\lib\site-packages\pip\_vendor\pyparsing.py", line 3783, in parseImpl
>     raise ParseException(instring, loc, self.errmsg, self)
> pip._vendor.pyparsing.ParseException: Expected stringEnd, found '['  (at char 11), (line:1, col:12)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "e:\anaconda\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
>     status = self.run(options, args)
>   File "e:\anaconda\lib\site-packages\pip\_internal\commands\install.py", line 362, in run
>     wheel_cache
>   File "e:\anaconda\lib\site-packages\pip\_internal\cli\req_command.py", line 238, in populate_requirement_set
>     wheel_cache=wheel_cache
>   File "e:\anaconda\lib\site-packages\pip\_internal\req\constructors.py", line 395, in install_req_from_line
>     parts = parse_req_from_line(name, line_source)
>   File "e:\anaconda\lib\site-packages\pip\_internal\req\constructors.py", line 347, in parse_req_from_line
>     extras = convert_extras(extras_as_string)
>   File "e:\anaconda\lib\site-packages\pip\_internal\req\constructors.py", line 78, in convert_extras
>     return Requirement("placeholder" + extras.lower()).extras
>   File "e:\anaconda\lib\site-packages\pip\_vendor\packaging\requirements.py", line 97, in __init__
>     requirement_string[e.loc : e.loc + 8], e.msg
> pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[--upgra'": Expected stringEnd

 or `python3 setup.py install`... doesn't say anything in the command prompt. I'm using **Anaconda** cmd for installation. It doesn't work with Windows cmd either. Thank you for your help.

**Comment by Clorky** [comment]
Fixed. Had to add pip to PATH and update it as well. Don't know what exactly was the issue.
